import { AlertCircle, CheckCircle2, Inbox, LoaderCircle, X } from 'lucide-react'

const styles = { primary: 'bg-brand-600 text-white hover:bg-brand-700 shadow-sm', secondary: 'bg-white text-ink border hover:bg-slate-50', danger: 'bg-rose-600 text-white hover:bg-rose-700' }
export function Button({ children, variant = 'primary', className = '', ...props }) { return <button className={`inline-flex items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-brand-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} {...props}>{children}</button> }
export function Card({ children, className = '' }) { return <section className={`rounded-xl border bg-white shadow-panel ${className}`}>{children}</section> }
export function Input({ label, className = '', ...props }) { return <label className="block text-sm font-medium text-slate-700">{label && <span className="mb-1.5 block">{label}</span>}<input className={`w-full rounded-lg border bg-white px-3 py-2.5 text-sm outline-none transition placeholder:text-slate-400 focus:border-brand-500 focus:ring-2 focus:ring-brand-100 ${className}`} {...props} /></label> }
export function Select({ label, children, className = '', ...props }) { return <label className="block text-sm font-medium text-slate-700">{label && <span className="mb-1.5 block">{label}</span>}<select className={`w-full rounded-lg border bg-white px-3 py-2.5 text-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-100 ${className}`} {...props}>{children}</select></label> }
export function Badge({ children, className = '' }) { return <span className={`inline-flex items-center rounded-full px-2.5 py-1 text-xs font-semibold ${className}`}>{children}</span> }
const statusStyles = { NEW: 'bg-amber-100 text-amber-800', ASSIGNED: 'bg-blue-100 text-blue-800', ACCEPTED: 'bg-violet-100 text-violet-800', ON_THE_WAY: 'bg-cyan-100 text-cyan-800', COMPLETED: 'bg-emerald-100 text-emerald-800', FAILED: 'bg-rose-100 text-rose-800', Available: 'bg-emerald-100 text-emerald-800', 'On job': 'bg-amber-100 text-amber-800' }
export function StatusBadge({ status }) { return <Badge className={statusStyles[status] || 'bg-slate-100 text-slate-700'}>{String(status).replaceAll('_', ' ')}</Badge> }
export function PageHeader({ eyebrow, title, description, action }) { return <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="mb-1 text-xs font-bold uppercase tracking-wider text-brand-600">{eyebrow}</p>}<h1 className="text-2xl font-bold tracking-tight text-ink sm:text-3xl">{title}</h1>{description && <p className="mt-1.5 max-w-2xl text-sm text-slate-500">{description}</p>}</div>{action}</div> }
export function EmptyState({ title = 'Nothing here yet', description = 'There are no items to show right now.' }) { return <div className="flex flex-col items-center px-5 py-14 text-center"><span className="mb-4 rounded-full bg-slate-100 p-3 text-slate-500"><Inbox size={24} /></span><h3 className="font-semibold">{title}</h3><p className="mt-1 max-w-xs text-sm text-slate-500">{description}</p></div> }
export function LoadingState() { return <div className="flex items-center justify-center gap-2 py-14 text-sm text-slate-500"><LoaderCircle className="animate-spin" size={18} />Loading</div> }
export function Modal({ open, title, children, onClose }) { if (!open) return null; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-md rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-bold">{title}</h2><button onClick={onClose} className="rounded p-1 text-slate-500 hover:bg-slate-100"><X size={18} /></button></div><div className="p-5">{children}</div></div></div> }
export function ConfirmationDialog({ open, title = 'Confirm action', description, onCancel, onConfirm }) { return <Modal open={open} title={title} onClose={onCancel}><div className="flex gap-3"><AlertCircle className="mt-0.5 text-amber-500" /><p className="text-sm text-slate-600">{description}</p></div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onCancel}>Cancel</Button><Button onClick={onConfirm}>Confirm</Button></div></Modal> }
export function SuccessIcon() { return <span className="inline-flex rounded-full bg-emerald-100 p-2 text-emerald-600"><CheckCircle2 /></span> }
